# Generated by Django 4.1.2 on 2024-01-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Geography',
            field=models.BigIntegerField(),
        ),
    ]
